export const GAME_CONFIG = {
  viewport: {
    width: 1600,
    height: 900,
  },
  world: {
    width: 5400,
    height: 900,
    outOfBoundsMargin: 100,
    verticalOutOfBoundsMargin: 1600,
  },
  physics: {
    stepHz: 180,
    trajectorySampleHz: 30,
    gravity: 900,
    windAccelerationScale: 0.2,
    minSpeed: 800,
    maxSpeed: 2900,
    maxFlightSeconds: 10,
  },
  aiming: {
    minAngleDeg: 10,
    maxAngleDeg: 80,
    minPower: 20,
    maxPower: 100,
    initialAngleDeg: 20,
    initialPower: 100,
    previewRatio: 0.25,
    previewMaxDistance: 1050,
  },
  battle: {
    initialPhase: "aiming",
    initialActivePlayerId: "left",
    initialTurnNumber: 1,
    resultDisplayMs: 1150,
    cameraPanMs: 950,
  },
  catapult: {
    maxHealth: 100,
    visualScale: 0.52,
    colliderWidth: 62,
    colliderHeight: 50,
    launchOffsetX: 11,
    launchOffsetY: -21,
  },
  knights: {
    maxHealth: 75,
    stepsToVictory: 10,
    spawnOffset: 150,
    targetOffset: 100,
    colliderWidth: 110,
    colliderHeight: 60,
    damageCoefficients: {
      stone: 1,
      fire: 1.33,
      ice: 1.25,
      diamond: 0.75,
      bomb: 1.15,
    },
  },
  repair: {
    healthRatio: 0.25,
  },
  projectiles: {
    stone: {
      radius: 9,
      baseDamage: 25,
      windFactor: 1,
      launchSpeedMultiplier: 0.96,
      playbackScale: 1.75,
      initialAmmo: null,
      tint: 0xffffff,
      relativeMass: 1,
    },
    fire: {
      radius: 8,
      baseDamage: 15,
      windFactor: 1,
      launchSpeedMultiplier: 1.02,
      playbackScale: 1.62,
      initialAmmo: 2,
      tint: 0xff7a45,
      relativeMass: 0.72,
    },
    ice: {
      radius: 8,
      baseDamage: 12,
      windFactor: 1,
      launchSpeedMultiplier: 0.93,
      playbackScale: 1.82,
      initialAmmo: 2,
      tint: 0x8fe8ff,
      relativeMass: 0.84,
    },
    diamond: {
      radius: 7,
      baseDamage: 35,
      windFactor: 0.25,
      launchSpeedMultiplier: 0.92,
      playbackScale: 1.9,
      initialAmmo: 1,
      tint: 0xb8f4ff,
      relativeMass: 1.18,
    },
    bomb: {
      radius: 11,
      baseDamage: 5,
      windFactor: 1,
      launchSpeedMultiplier: 0.9,
      playbackScale: 2,
      initialAmmo: 1,
      tint: 0x6f7891,
      relativeMass: 1.28,
    },
  },
  damage: {
    referenceImpactSpeed: 700,
    minImpactFactor: 0.6,
    maxImpactFactor: 1.2,
    defaultMaterialCoefficient: 1,
    energyReferenceSpeed: 1800,
    minimumEnergyFactor: 0.45,
    maximumEnergyFactor: 1.55,
    minimumIncidenceFactor: 0.5,
    catapultHitZoneCoefficients: {
      arm: 1.15,
      frame: 0.82,
      wheels: 0.95,
    },
  },
  displacement: {
    minimumImpactSpeed: 900,
    speedToDistance: 0.018,
    maximumDistance: 64,
    minimumDistance: 5,
    worldMargin: 120,
    minimumOpponentGap: 160,
    maximumTerrainStep: 32,
    searchStep: 4,
    hitZoneMobility: {
      arm: 0.55,
      frame: 0.82,
      wheels: 1.2,
    },
    weatherMobility: {
      superheat: 1,
      rain: 1.12,
      snow: 1.3,
      sandstorm: 0.9,
    },
  },
  projectileEffects: {
    ice: {
      frozenMaxPower: 70,
    },
    diamond: {
      protectionResistanceIgnored: 0.5,
    },
    bomb: {
      explosionRadius: 160,
      maxExplosionDamage: 30,
    },
  },
  protections: {
    castle: {
      cost: 1,
      maxDurability: 100,
      width: 140,
      height: 260,
      firstInterceptPenalty: 0,
      damageCoefficients: {
        stone: 1,
        fire: 0.65,
        ice: 0.75,
        diamond: 1.25,
        bomb: 1.1,
      },
    },
  },
  arenaObstacles: {
    fortress: {
      maxDurability: 90,
      damageCoefficients: {
        stone: 1,
        fire: 0.7,
        ice: 0.8,
        diamond: 1.1,
        bomb: 1,
      },
    },
    rock: {
      maxDurability: 120,
      damageCoefficients: {
        stone: 1,
        fire: 0.5,
        ice: 0.8,
        diamond: 1.2,
        bomb: 0.9,
      },
    },
  },
  placement: {
    catapultSlots: {
      left: [480, 600, 720],
      right: [4920, 4800, 4680],
    },
    protectionSlotCenters: {
      left: [480, 600, 720],
      right: [4920, 4800, 4680],
    },
    castleWallCenters: {
      left: [
        [480],
        [600],
        [720],
      ],
      right: [
        [4920],
        [4800],
        [4680],
      ],
    },
    protectionBudget: 1,
    maximumProtectionCount: 1,
  },
  weather: {
    defaultMatchSeed: 0x7a2c_91e5,
    superheat: {
      windMinimum: -30,
      windMaximum: 30,
      burnDamagePerTurn: 8,
      burnDurationTurns: 2,
      freezeDurationTurns: 1,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 1,
      previewRatio: 0.25,
    },
    rain: {
      windMinimum: -50,
      windMaximum: 50,
      burnDamagePerTurn: 5,
      burnDurationTurns: 1,
      freezeDurationTurns: 1,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 1,
      previewRatio: 0.25,
    },
    snow: {
      windMinimum: -40,
      windMaximum: 40,
      burnDamagePerTurn: 5,
      burnDurationTurns: 2,
      freezeDurationTurns: 2,
      launchSpeedMultiplier: 0.92,
      gravityMultiplier: 0.8464,
      previewRatio: 0.25,
    },
    sandstorm: {
      windMinimum: -120,
      windMaximum: 120,
      burnDamagePerTurn: 5,
      burnDurationTurns: 2,
      freezeDurationTurns: 1,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 1,
      previewRatio: 0.1,
    },
  },
} as const;
