export const GAME_CONFIG = {
  viewport: {
    width: 1600,
    height: 900,
  },
  world: {
    width: 5400,
    height: 900,
    outOfBoundsMargin: 100,
    verticalOutOfBoundsMargin: 1600,
  },
  physics: {
    stepHz: 180,
    trajectorySampleHz: 30,
    gravity: 900,
    windAccelerationScale: 0.2,
    minSpeed: 800,
    maxSpeed: 2900,
    maxFlightSeconds: 10,
  },
  aiming: {
    minAngleDeg: 10,
    maxAngleDeg: 80,
    minPower: 20,
    maxPower: 100,
    initialAngleDeg: 20,
    initialPower: 100,
    previewRatio: 0.25,
    previewMaxDistance: 1050,
  },
  battle: {
    initialPhase: "aiming",
    initialActivePlayerId: "left",
    initialTurnNumber: 1,
    resultDisplayMs: 600,
    cameraPanMs: 950,
  },
  catapult: {
    maxHealth: 100,
    visualScale: 0.82,
    colliderWidth: 72,
    colliderHeight: 66,
    launchOffsetX: 28,
    launchOffsetY: -52,
  },
  projectiles: {
    stone: {
      radius: 9,
      baseDamage: 25,
      windFactor: 1,
      launchSpeedMultiplier: 0.96,
      playbackScale: 1.75,
      initialAmmo: null,
      tint: 0xffffff,
    },
    fire: {
      radius: 8,
      baseDamage: 15,
      windFactor: 1,
      launchSpeedMultiplier: 1.02,
      playbackScale: 1.62,
      initialAmmo: 2,
      tint: 0xff7a45,
    },
    ice: {
      radius: 8,
      baseDamage: 12,
      windFactor: 1,
      launchSpeedMultiplier: 0.93,
      playbackScale: 1.82,
      initialAmmo: 2,
      tint: 0x8fe8ff,
    },
    diamond: {
      radius: 7,
      baseDamage: 35,
      windFactor: 0.25,
      launchSpeedMultiplier: 0.92,
      playbackScale: 1.9,
      initialAmmo: 1,
      tint: 0xb8f4ff,
    },
    bomb: {
      radius: 11,
      baseDamage: 5,
      windFactor: 1,
      launchSpeedMultiplier: 0.9,
      playbackScale: 2,
      initialAmmo: 1,
      tint: 0x6f7891,
    },
  },
  damage: {
    referenceImpactSpeed: 700,
    minImpactFactor: 0.6,
    maxImpactFactor: 1.2,
    defaultMaterialCoefficient: 1,
  },
  projectileEffects: {
    ice: {
      frozenMaxPower: 70,
    },
    diamond: {
      protectionResistanceIgnored: 0.5,
    },
    bomb: {
      explosionRadius: 160,
      maxExplosionDamage: 30,
    },
  },
  protections: {
    wood: {
      cost: 1,
      maxDurability: 30,
      width: 70,
      height: 92,
      firstInterceptPenalty: 0,
      damageCoefficients: {
        stone: 1,
        fire: 1.5,
        ice: 0.8,
        diamond: 1.2,
        bomb: 1,
      },
    },
    net: {
      cost: 1,
      maxDurability: 20,
      width: 62,
      height: 112,
      firstInterceptPenalty: 5,
      damageCoefficients: {
        stone: 0.7,
        fire: 1,
        ice: 0.8,
        diamond: 1.4,
        bomb: 1,
      },
    },
    metal: {
      cost: 2,
      maxDurability: 55,
      width: 58,
      height: 124,
      firstInterceptPenalty: 0,
      damageCoefficients: {
        stone: 0.6,
        fire: 0.3,
        ice: 0.7,
        diamond: 1,
        bomb: 0.8,
      },
    },
  },
  arenaObstacles: {
    fortress: {
      maxDurability: 90,
      damageCoefficients: {
        stone: 1,
        fire: 0.7,
        ice: 0.8,
        diamond: 1.1,
        bomb: 1,
      },
    },
    rock: {
      maxDurability: 120,
      damageCoefficients: {
        stone: 1,
        fire: 0.5,
        ice: 0.8,
        diamond: 1.2,
        bomb: 0.9,
      },
    },
  },
  placement: {
    catapultSlots: {
      left: [480, 600, 720],
      right: [4920, 4800, 4680],
    },
    protectionSlotCenters: {
      left: [330, 400, 820, 900, 970],
      right: [5070, 5000, 4580, 4500, 4430],
    },
    protectionBudget: 4,
    maximumProtectionCount: 3,
    maximumMetalCount: 1,
  },
  weather: {
    defaultMatchSeed: 0x7a2c_91e5,
    superheat: {
      windMinimum: -30,
      windMaximum: 30,
      burnDamagePerTurn: 8,
      burnDurationTurns: 2,
      freezeDurationTurns: 1,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 1,
      previewRatio: 0.25,
    },
    rain: {
      windMinimum: -50,
      windMaximum: 50,
      burnDamagePerTurn: 5,
      burnDurationTurns: 1,
      freezeDurationTurns: 1,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 1,
      previewRatio: 0.25,
    },
    snow: {
      windMinimum: -40,
      windMaximum: 40,
      burnDamagePerTurn: 5,
      burnDurationTurns: 2,
      freezeDurationTurns: 2,
      launchSpeedMultiplier: 0.92,
      gravityMultiplier: 0.8464,
      previewRatio: 0.25,
    },
    sandstorm: {
      windMinimum: -120,
      windMaximum: 120,
      burnDamagePerTurn: 5,
      burnDurationTurns: 2,
      freezeDurationTurns: 1,
      launchSpeedMultiplier: 1,
      gravityMultiplier: 1,
      previewRatio: 0.1,
    },
  },
} as const;
